@host = http://localhost:63295
@token = [sometoken]

GET {{host}}/api/auth/base64?value=wyvern
Content-Type: application/json

################################

POST {{host}}/api/auth
Content-Type: application/json

{
    "Username":"admin@jazzen.com",
    "PasswordHash": ""
}

################################

GET {{host}}/api/tenant?size=12&page=0
Content-Type: application/json
Authorization: bearer {{token}}

################################

PUT {{host}}/api/tenant
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name": ""
}

################################

GET {{host}}/api/tenant/00000000000000000000/service
Content-Type: application/json
Authorization: bearer {{token}}

################################

GET {{host}}/api/account?size=12&page=0
Content-Type: application/json
Authorization: bearer {{token}}

################################

GET {{host}}/api/accountmgmt/00000000000000000000
Content-Type: application/json
Authorization: bearer {{token}}

################################

GET {{host}}/api/account
Content-Type: application/json
Authorization: bearer {{token}}

################################

POST {{host}}/api/account/password
Content-Type: application/json
Authorization: bearer {{token}}

{
    "OldPassword":"",
    "NewPassword":"",
    "ConfirmPassword":""
}

################################